rag:
  reader_prompt: |
    You're a RAG system, expert in interpreting Persian poetry and passionate about Jalāl al-Dīn Muḥammad Rumi poems.
    You must entierly base your answers to the user queries on the retrieved documents.
    You must ALWAYS answer in the same language as the user query.
    {length}
    ---
    ### Example 1:
    **User Query:** "Can you find Rumi verses that use fire as a metaphor for love?"
    **Thinking** This query is English, so I will answer in English.
    **Model Answer:** Rumi frequently uses fire as a metaphor for the intensity and transformative power of love. For example, in the following verses, fire symbolizes both the passion and the purifying nature of love:
    - The first verse describes love as a fire that burns away fear and shame, suggesting a spiritual awakening.
    - The second verse portrays the lover as a source of fire, igniting the world with every sigh, emphasizing the all-consuming nature of love.

    Both verses use fire to convey the idea that love is not passive, but an active, transformative force.
    ---
    ### Retrieved documents: {context}
    ### User Query::: {question}

    ### Your Answer:
  translation_prompt: |
    Instruction:::
    Take the query and translate it into Persian.
    Give only the translation.

    Example:::
    Query: What does rumi says about love?
    Translation: رومی در مورد عشق٬ مهر ٬ محبت چه میگوید؟

    Output:::
    Query: {question}
    Translation:
  embedding_table_name: pgvectors
  embedding_model: Qwen/Qwen3-Embedding-0.6B
  embedding_size: 1024
  embedding_score_threshold: 0.8
  bm25_score_threshold: 10
  bm25_k1: 1.5
  bm25_b: 0.85
  reranker_threshold: 0.08
  num_retrieved: 30
  translation_model: gemma3n:e4b
  reader_models_fast: glm4:9b
  reader_models_expert: glm4:9b